on: push
name: Make stub

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  collate:
    name: collate ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest
        - windows-latest
        - ubuntu-latest
        python:
        - '3.14'
        - '3.13'
        - '3.12'
        - '3.11'
        - '3.10'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      id: can-setup-python
      continue-on-error: true
      with:
        python-version: ${{ matrix.python }}

    - name: Collate errnos
      if: ${{ !cancelled() && steps.can-setup-python.outcome == 'success' }}
      run: |
        python collate.py | tee errnos.py

    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: errnos-${{ matrix.os }}-${{ matrix.python }}
        path: errnos.py

  combine:
    needs: collate
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Display collected outputs
      run: |
        tee -a combined.py <<< 'import sys'
        find . -name "errnos.py" -type f | while read -r file; do
          cat "$file" | tee -a combined.py
        done

    - name: Upload combined errnos
      uses: actions/upload-artifact@v4
      with:
        name: combined
        path: combined.py

  dedupe:
    needs: combine
    name: dedupe (using ${{ matrix.os }} ${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        python:
        - '3.14'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Generate deduped stub
      run: |
        python dedupe.py combined/combined.py | tee errno.pyi

    - name: Upload deduped stub
      uses: actions/upload-artifact@v4
      with:
        name: out
        path: errno.pyi


  verify:
    needs: dedupe
    name: verify ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest
        - windows-latest
        - ubuntu-latest
        python:
        - '3.14'
        - '3.13'
        - '3.12'
        - '3.11'
        - '3.10'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Verify generated stub
      run: |
        python verify.py out/errno.pyi
