on: push
name: Run stuff

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# defaults:
#   run:
#     shell: bash

jobs:
  run-stuff:
    name: ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest
        - windows-latest
        - ubuntu-latest
        python:
        - '3.14'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      id: can-setup-python
      continue-on-error: true
      with:
        python-version: ${{ matrix.python }}

    - name: Run stuff
      if: ${{ !cancelled() && steps.can-setup-python.outcome == 'success' }}
      run: |
        python -X dev stuff.py

